# this is inspired from https://github.com/combiz/scFlow/blob/master/.github/workflows/r_package.yaml
# and relies on https://github.com/docker/build-push-action
name: ci

on:
  push:
  pull_request:

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}